# Generated by Django 2.0.5 on 2018-07-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cruds', '0006_vendedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.CharField(max_length=100)),
                ('data_entrega', models.DateField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_pgto', models.CharField(max_length=100)),
                ('valor_entrada', models.CharField(max_length=100)),
                ('parcelas', models.IntegerField(max_length=100)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruds.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_over', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cod_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruds.Produtos')),
            ],
        ),
        migrations.AddField(
            model_name='atendimentos',
            name='cod_compra',
            field=models.ManyToManyField(to='atendimentos.Compras'),
        ),
        migrations.AddField(
            model_name='atendimentos',
            name='cod_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruds.Vendedores'),
        ),
    ]
