# Generated by Django 2.0.5 on 2018-07-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentos',
            name='parcelas',
            field=models.IntegerField(),
        ),
    ]
