# Generated by Django 2.0.5 on 2018-07-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('fornecedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=40)),
                ('nome_prop', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tipo_fornecedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=100)),
                ('desc_produto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruds.Fornecedores')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruds.Medidas')),
            ],
        ),
    ]
