# Generated by Django 2.0.5 on 2018-07-01 05:34

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='fornecedor_id',
            new_name='cod_fornecedor',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='fornecedor',
            new_name='cod_fornecedor',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='id',
            new_name='cod_produto',
        ),
    ]
