# Generated by Django 2.0.5 on 2018-07-01 05:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('cruds', '0002_auto_20180701_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='cod_fornecedor',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='cod_produto',
            new_name='id',
        ),
    ]
