# Generated by Django 2.0.5 on 2018-07-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0003_auto_20180701_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='cod_fornecedor',
            new_name='fornecedor',
        ),
    ]
