# Generated by Django 2.0.5 on 2018-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0004_auto_20180701_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('insc_estadual', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('contato_cel', models.CharField(max_length=100)),
                ('contato_tel', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
            ],
        ),
    ]
