# Generated by Django 2.0.5 on 2018-07-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0005_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vendedor', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
    ]
